package com.v2soft.training.entity;
// Generated Oct 9, 2019, 1:30:22 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * AddressType generated by hbm2java
 */
public class AddressType implements java.io.Serializable {

	private int id;
	private String type;
	private Set<EmployeeAddress> employeeAddresses = new HashSet<EmployeeAddress>(0);

	public AddressType() {
	}

	public AddressType(int id, String type) {
		this.id = id;
		this.type = type;
	}

	public AddressType(int id, String type, Set<EmployeeAddress> employeeAddresses) {
		this.id = id;
		this.type = type;
		this.employeeAddresses = employeeAddresses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<EmployeeAddress> getEmployeeAddresses() {
		return this.employeeAddresses;
	}

	public void setEmployeeAddresses(Set<EmployeeAddress> employeeAddresses) {
		this.employeeAddresses = employeeAddresses;
	}

}
