package com.v2soft.training.entity;
// Generated Oct 9, 2019, 1:30:22 PM by Hibernate Tools 5.1.10.Final

/**
 * EmployeeAddress generated by hbm2java
 */
public class EmployeeAddress implements java.io.Serializable {

	private EmployeeAddressId id;
	private AddressType addressType;
	private Employeeinfo employeeinfo;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String zipCode;
	private String zip4;

	public EmployeeAddress() {
	}

	public EmployeeAddress(EmployeeAddressId id, AddressType addressType, Employeeinfo employeeinfo,
			String addressLine1, String city, String state, String zipCode) {
		this.id = id;
		this.addressType = addressType;
		this.employeeinfo = employeeinfo;
		this.addressLine1 = addressLine1;
		this.city = city;
		this.state = state;
		this.zipCode = zipCode;
	}

	public EmployeeAddress(EmployeeAddressId id, AddressType addressType, Employeeinfo employeeinfo,
			String addressLine1, String addressLine2, String city, String state, String zipCode, String zip4) {
		this.id = id;
		this.addressType = addressType;
		this.employeeinfo = employeeinfo;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.state = state;
		this.zipCode = zipCode;
		this.zip4 = zip4;
	}

	public EmployeeAddressId getId() {
		return this.id;
	}

	public void setId(EmployeeAddressId id) {
		this.id = id;
	}

	public AddressType getAddressType() {
		return this.addressType;
	}

	public void setAddressType(AddressType addressType) {
		this.addressType = addressType;
	}

	public Employeeinfo getEmployeeinfo() {
		return this.employeeinfo;
	}

	public void setEmployeeinfo(Employeeinfo employeeinfo) {
		this.employeeinfo = employeeinfo;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getZip4() {
		return this.zip4;
	}

	public void setZip4(String zip4) {
		this.zip4 = zip4;
	}

}
